{% set name = "akernel" %}
{% set version = "0.0.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b8be613fb443845e246bdfc15c83258676af4dcb7919dd6da48149ae6a9a86ed

build:
  noarch: python
  number: 0
  entry_points:
    - akernel = akernel.akernel:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - pyzmq
    - typer
    - click <8
    - python-dateutil
    - colorama
    - gast

test:
  commands:
    - akernel --help
    - test -f ${PREFIX}/share/jupyter/kernels/akernel/kernel.json  # [unix]
    - if not exist %PREFIX%\share\jupyter\kernels\akernel\kernel.json (exit 1)  # [win]

about:
  home: https://github.com/davidbrochart/akernel
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An asynchronous Python Jupyter kernel
  dev_url: https://github.com/davidbrochart/akernel

extra:
  recipe-maintainers:
    - davidbrochart
