{% set name = "akernel" %}
{% set version = "0.0.22" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: dbabd167daba7871a97e35846d7570f00e8c97191cc8a67361c228ee5c5356d9

build:
  noarch: python
  number: 0
  entry_points:
    - akernel = akernel.akernel:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - pyzmq
    - typer >=0.4.0
    - python-dateutil
    - colorama
    - gast >=0.5.3
    - ipyx >=0.1.7
    - zict

test:
  commands:
    - akernel --help
    - test -f ${PREFIX}/share/jupyter/kernels/akernel/kernel.json  # [unix]
    - if not exist %PREFIX%\share\jupyter\kernels\akernel\kernel.json (exit 1)  # [win]

about:
  home: https://github.com/davidbrochart/akernel
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Asynchronous, reactive Python Jupyter kernel
  dev_url: https://github.com/davidbrochart/akernel

extra:
  recipe-maintainers:
    - davidbrochart
