{% set name = "akernel" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1a7da70893586657c886fdc5fb042aa49713d6ea0f4277d380b847938cd4d968

build:
  noarch: python
  number: 0
  entry_points:
    - akernel = akernel.akernel:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - hatchling
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - pyzmq
    - typer >=0.4.0
    - python-dateutil
    - colorama
    - gast >=0.5.3
    - comm >=0.1.3,<1
    - ipyx >=0.1.7
    - zict

test:
  requires:
    - python {{ python_min }}
  commands:
    - akernel --help
    - test -f ${PREFIX}/share/jupyter/kernels/akernel/kernel.json  # [unix]
    - if not exist %PREFIX%\share\jupyter\kernels\akernel\kernel.json (exit 1)  # [win]

about:
  home: https://github.com/davidbrochart/akernel
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Asynchronous, reactive Python Jupyter kernel
  dev_url: https://github.com/davidbrochart/akernel

extra:
  recipe-maintainers:
    - davidbrochart
