{% set name = "akernel" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: dd6553f640dd986475f61d71c441fb378c03d30e58151b653397c90356925def

build:
  noarch: python
  number: 0
  entry_points:
    - akernel = akernel.akernel:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - hatchling
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - python-dateutil
    - colorama
    - gast >=0.6.0,<0.7.0
    - comm >=0.1.3,<1
    - anyio

test:
  requires:
    - python {{ python_min }}
    - pip
    - zmq-anyio >=0.3.9,<0.4.0
    - typer >=0.4.0
  commands:
    - pip check
    - akernel --help
    - test -f ${PREFIX}/share/jupyter/kernels/akernel/kernel.json  # [unix]
    - if not exist %PREFIX%\share\jupyter\kernels\akernel\kernel.json (exit 1)  # [win]
  imports:
    - akernel

about:
  home: https://github.com/davidbrochart/akernel
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Asynchronous, reactive Python Jupyter kernel
  dev_url: https://github.com/davidbrochart/akernel

extra:
  recipe-maintainers:
    - davidbrochart
